### ISSUE TITLE
是否支持全局配置，比如在application初始化的时候配置好所有的参数。

### ISSUE THREAD

**Issue by z2700589** [songlongGithub/uTakePhoto#1]
RT

**Comment by songlongGithub** [comment]
已添加，请查看1.0.6

**Comment by z2700589** [comment]
👍👍好快

---原始邮件---
发件人: "songlongGithub"<notifications@github.com&gt;
发送时间: 2019年11月4日(星期一) 下午4:45
收件人: "songlongGithub/uTakePhoto"<uTakePhoto@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"z2700589"<471846788@qq.com&gt;;
主题: Re: [songlongGithub/uTakePhoto] 是否支持全局配置，比如在application初始化的时候配置好所有的参数。 (#1)



已添加，请查看1.0.6
