### ISSUE TITLE
1.1.2版本 存在问题呢，选取剪裁后，uri为空

### ISSUE THREAD

**Issue by dacaoyuan** [songlongGithub/uTakePhoto#13]
1.1.1和1.1.2版本 存在问题呢，选取剪裁后，uri为空，改成 1.1.0 Android11以下没问题。

**Comment by J1aDong** [comment]
+1

**Comment by KangGuiYang** [comment]
最后解决了吗？

**Comment by KangGuiYang** [comment]
> 1.1.1和1.1.2版本 存在问题呢，选取剪裁后，uri为空，改成 1.1.0 Android11以下没问题。

你好，请问后来解决了吗 我现在也遇到了这个问题

**Comment by dacaoyuan** [comment]
没有呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月19日(星期一) 晚上7:23
收件人: ***@***.***&gt;; 
抄送: "大草原 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [songlongGithub/uTakePhoto] 1.1.2版本 存在问题呢，选取剪裁后，uri为空 (#13)





  
1.1.1和1.1.2版本 存在问题呢，选取剪裁后，uri为空，改成 1.1.0 Android11以下没问题。
  
你好，请问后来解决了吗 我现在也遇到了这个问题

**Comment by songlongGithub** [comment]
1.2.0已修复
