### ISSUE TITLE
API调用问题

### ISSUE THREAD

**Issue by maxrco** [songlongGithub/uTakePhoto#3]
``private` fun showMenuDialog() {
        val takePhotoManager = UTakePhoto.with(this)
        val items = arrayOf("相册", "拍照", "取消")
        MenuDialogBuilder(context)
            .addItems(items) { dialog, which ->
                when (which) {
                    0 -> takePhotoManager.openAlbum()
                    1 -> takePhotoManager.openCamera()
//                    2 -> ToastUtils.showShort("取消")
                }
                dialog.dismiss()
            }
            .create(R.style.QMUI_Dialog).show()

        takePhotoManager.build(object : ITakePhotoResult {
            override fun takeFailure(ex: TakeException?) {

            }

            override fun takeSuccess(uriList: MutableList<Uri>?) {
            }

            override fun takeCancel() {
            }

        })
    }`

必须要调用2次,第1次永远出不来

**Comment by songlongGithub** [comment]
我按照你的方式，没有复现出来

**Comment by maxrco** [comment]
每次调用必须重新UTakePhoto.with(this)才行啊
