### ISSUE TITLE
问题反馈  

### ISSUE THREAD

**Issue by cx52** [songlongGithub/uTakePhoto#7]
三星一款手机7.0  拍照后 图片加载出来黑屏   or 一直在加载中

华为荣耀v20 andriod Q  图片有时候一直在加载中，然后结束了

**Comment by cx52** [comment]
系统剪裁没问题，库自带剪裁是有问题的。好像很多机子没适配好。

**Comment by cx52** [comment]
LoadBitmapTask 在进行这个异步的时候，偶尔图太大了。异步加载不出来，直接返回了。
或者要加载很久，自带剪裁框才出来 用户等的都不耐烦了。系统剪裁框可以秒出来，很ok
现在手机像素高，图片一般都是很大的。
另外三星那个手机  库自带剪裁框打开黑屏  系统剪裁狂完全没问题  这个查不出来了

**Comment by cx52** [comment]
平均你那个异步 加载一个20M图片 要3-10分钟多。一直在那里loadding
用户还以为死机了

希望作者修复

**Comment by songlongGithub** [comment]
我测试一下大图，稍后修改

**Comment by songlongGithub** [comment]
我测试50m的图片加载最多2秒，华为荣耀v20我这边也测试了一下，没发现问题，LoadBitmapTask只是计算sampleSize后获取bitmap，理论不会那么慢的，你可以把图片发我邮箱，我测试一下616727136@qq.com

**Comment by cx52** [comment]
UTakePhoto.init(null,null);
                        File PICTURES = getExternalFilesDir(Environment.DIRECTORY_PICTURES);
                        filex = new File(PICTURES + "/" + "crop" + "/head.png");
                        CompressConfig compressConfig = new CompressConfig.Builder()
                                .setFocusAlpha(false)//是否支持透明度

                                .setLeastCompressSize(100)//最小压缩尺寸
                                .setTargetUri(Uri.fromFile(filex))//压缩图片储存路径
                                .create();

                        CropOptions cropOptions = new CropOptions.Builder()
                                .setAspectX(800).setAspectY(500)
                                .setOutputX(320).setOutputY(225)
                                .setWithOwnCrop(true)//使用系统裁剪还是自带裁剪
                                .create();

                        UTakePhoto.with(EditXiaoqu.this).openCamera().setCompressConfig(compressConfig).setCrop(cropOptions).build(new ITakePhotoResult() {
                            @Override
                            public void takeSuccess(List<Uri> uriList) {
....



那我把代码发给你吧。就这样一段，你先看看有问题不。
andriod10 荣耀v20  
图片就是 v20相机调到分辨率最高ai  随便拍一张大概在20MB左右

**Comment by cx52** [comment]
还有这个不是必现。有时好，有时坏。所以不知道原因的
有时候连着几次坏了，再重开app又好了。但我这台andriod10 v20出现的比较多。
你看看是不是我代码错误导致的

**Comment by cx52** [comment]
我拿你demo的例子多试了几次就不行了

**Comment by cx52** [comment]
选择照片， 自带裁剪，宽和高 320  225    压缩：否    旋转：否    然后找你自己拍的20M的图片，前两次正常，后面就挂了

**Comment by cx52** [comment]
![image](https://user-images.githubusercontent.com/63282983/82993994-0a504e00-a034-11ea-9f36-f58f7e8f7956.png)
我录了视频，但是不能发，我截图下来了。这样配置，然后进去，多试几次，就不行了

**Comment by cx52** [comment]
有时候秒出，有时候能加载2小时。有时候10分钟就出来

图给你了
[11590567033_.pic_hd.jpg.zip](https://github.com/songlongGithub/uTakePhoto/files/4687393/11590567033_.pic_hd.jpg.zip)

**Comment by allnan** [comment]
同题主，遇到了这个问题。

**Comment by cx52** [comment]
@allnan 我自己改好了代码，还是记得改了什么，还是用了别的方式，记不清了。你在去发个议题吧，我过几天我把代码，拉下来，再帮你看看

**Comment by cx52** [comment]
@allnan 他不修复，这个问题永远是个问题

**Comment by allnan** [comment]
> @allnan 我自己改好了代码，还是记得改了什么，还是用了别的方式，记不清了。你在去发个议题吧，我过几天我把代码，拉下来，再帮你看看

兄弟不用麻烦了，我是接手的项目，我换个方式拿图片裁切就行。
